AWSTemplateFormatVersion: 2010-09-09
Resources:
  EcrRepository1:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: "kafka-streams-msk"
  EcrRepository2:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: "twitter-stream-producer"